### ISSUE TITLE
Library not compile with Swift 1.2

### ISSUE THREAD

**Issue by mhergon** [vyshane/geohash-tool#1]
Hi,

Is there any possibility to update the library to work with last version of Swift implementation?

Thanks!

**Comment by vyshane** [comment]
Sure, I'll look into it.

**Comment by mhergon** [comment]
Hi,

The main problem is with "@autoclosure" in "Result.swift" file.

Thanks!

**Comment by vyshane** [comment]
Thanks, fixed. Now compiles in Swift 1.2. I've removed the Result type for now. Returning nil on failure instead.

**Comment by mhergon** [comment]
Thanks!

While you made the changes, I tried to fix it and I changed "Result.swift" with this code. Later, I changed it on every place that "Ok" appears:

``` swift
import Foundation

public enum Result<AnyObject> {
    case Ok(Int)
    case OkC(Character)
    case Error(NSError)
}
```

Thanks again!

**Comment by vyshane** [comment]
That defeats the point of having a `Result` type though.
